import type { ChipProps, PinAttributeMap } from "@tscircuit/props";

/** Pimoroni Tiny 2350 — compact RP2350 header-ready board. */
export const PimoroniTiny2350_FOOTPRINT =
  "headermodule40_rows2_p2.54mm_py17.78mm_id1mm_od1.6mm_female_silkscreenborder_silkscreenlabel(Pimoroni Tiny 2350)" as const;

export const PimoroniTiny2350_PIN_LABELS = {
  pin1: ["GP0"],
  pin2: ["GP1"],
  pin3: ["GP2"],
  pin4: ["GP3"],
  pin5: ["GP4"],
  pin6: ["GP5"],
  pin7: ["GP6"],
  pin8: ["GP7"],
  pin9: ["GP8"],
  pin10: ["GP9"],
  pin11: ["GP10"],
  pin12: ["GP11"],
  pin13: ["GP12"],
  pin14: ["GP13"],
  pin15: ["GP14"],
  pin16: ["GP15"],
  pin17: ["GP16"],
  pin18: ["GP17"],
  pin19: ["GP18"],
  pin20: ["GP19"],
  pin21: ["GP20"],
  pin22: ["GP21"],
  pin23: ["GP22"],
  pin24: ["GP23"],
  pin25: ["GP24"],
  pin26: ["GP25"],
  pin27: ["GP26"],
  pin28: ["GP27"],
  pin29: ["GP28"],
  pin30: ["RUN"],
  pin31: ["ADC_VREF"],
  pin32: ["3V3_EN"],
  pin33: ["3V3"],
  pin34: ["VSYS"],
  pin35: ["VBUS"],
  pin36: ["GND1"],
  pin37: ["GND2"],
  pin38: ["GND3"],
  pin39: ["GND4"],
  pin40: ["GND5"],
} as const;

export const PimoroniTiny2350_PIN_ATTRIBUTES = {
  GP0: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP1: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP2: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP3: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP4: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP5: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP6: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP7: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP8: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP9: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP10: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP11: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP12: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP13: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP14: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP15: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP16: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP17: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP18: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP19: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP20: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP21: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP22: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP23: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP24: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP25: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP26: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP27: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  GP28: {
    isGpio: true,
    includeInBoardPinout: true,
    canUseInternalPullup: true,
    canUseInternalPulldown: true,
    canUseOpenDrain: true,
    canUsePushPull: true,
  },
  RUN: { includeInBoardPinout: true },
  ADC_VREF: { includeInBoardPinout: true },
  "3V3_EN": { includeInBoardPinout: true },
  "3V3": {
    providesPower: true,
    providesVoltage: "3.3V",
    includeInBoardPinout: true,
  },
  VSYS: {
    requiresPower: true,
    providesPower: true,
    includeInBoardPinout: true,
  },
  VBUS: {
    requiresPower: true,
    providesPower: true,
    includeInBoardPinout: true,
  },
  GND1: {
    requiresGround: true,
    providesGround: true,
    includeInBoardPinout: true,
  },
  GND2: {
    requiresGround: true,
    providesGround: true,
    includeInBoardPinout: true,
  },
  GND3: {
    requiresGround: true,
    providesGround: true,
    includeInBoardPinout: true,
  },
  GND4: {
    requiresGround: true,
    providesGround: true,
    includeInBoardPinout: true,
  },
  GND5: {
    requiresGround: true,
    providesGround: true,
    includeInBoardPinout: true,
  },
} as const satisfies Record<string, PinAttributeMap>;

type FixedProps =
  | "displayName"
  | "footprint"
  | "mfn"
  | "pinAttributes"
  | "pinLabels"
  | "pcbPinLabels"
  | "schHeight"
  | "schPinArrangement"
  | "schWidth";

export type PimoroniTiny2350Props = Omit<
  ChipProps<typeof PimoroniTiny2350_PIN_LABELS>,
  FixedProps
>;

export const PimoroniTiny2350 = (props: PimoroniTiny2350Props) => (
  <chip
    {...props}
    displayName="Pimoroni Tiny 2350"
    mfn="Pimoroni"
    footprint={PimoroniTiny2350_FOOTPRINT}
    pinLabels={PimoroniTiny2350_PIN_LABELS}
    pcbPinLabels={{
      pin1: "GP0",
      pin2: "GP1",
      pin3: "GP2",
      pin4: "GP3",
      pin5: "GP4",
      pin6: "GP5",
      pin7: "GP6",
      pin8: "GP7",
      pin9: "GP8",
      pin10: "GP9",
      pin11: "GP10",
      pin12: "GP11",
      pin13: "GP12",
      pin14: "GP13",
      pin15: "GP14",
      pin16: "GP15",
      pin17: "GP16",
      pin18: "GP17",
      pin19: "GP18",
      pin20: "GP19",
      pin21: "GP20",
      pin22: "GP21",
      pin23: "GP22",
      pin24: "GP23",
      pin25: "GP24",
      pin26: "GP25",
      pin27: "GP26",
      pin28: "GP27",
      pin29: "GP28",
      pin30: "RUN",
      pin31: "ADC_VREF",
      pin32: "3V3_EN",
      pin33: "3V3",
      pin34: "VSYS",
      pin35: "VBUS",
      pin36: "GND1",
      pin37: "GND2",
      pin38: "GND3",
      pin39: "GND4",
      pin40: "GND5",
    }}
    pinAttributes={PimoroniTiny2350_PIN_ATTRIBUTES}
    schWidth={2.8}
    schHeight={7.6}
    schPinArrangement={{
      leftSide: {
        direction: "top-to-bottom",
        pins: [
          "GP0",
          "GP1",
          "GP2",
          "GP3",
          "GP4",
          "GP5",
          "GP6",
          "GP7",
          "GP8",
          "GP9",
          "GP10",
          "GP11",
          "GP12",
          "GP13",
          "GP14",
          "GP15",
          "GP16",
          "GP17",
          "GP18",
          "GP19",
        ],
      },
      rightSide: {
        direction: "top-to-bottom",
        pins: [
          "GP20",
          "GP21",
          "GP22",
          "GP23",
          "GP24",
          "GP25",
          "GP26",
          "GP27",
          "GP28",
          "RUN",
          "ADC_VREF",
          "3V3_EN",
          "3V3",
          "VSYS",
          "VBUS",
          "GND1",
          "GND2",
          "GND3",
          "GND4",
          "GND5",
        ],
      },
    }}
  />
);
